name: Test Envirinment
on : [push]

jobs:
  test-environments:
    runs-on: ubuntu-latest
    steps:
    - name: check environment variable
      run: |
        echo "Hello ${{ secrets.MY_SEC }}" >> secrets.txt
        cat secrets.txt