name: Test Envirinment
on : [push]

jobs:
  test-environments:
    runs-on: ubuntu-latest
    steps:
    - name: check environment variable
      env:
        MY_SEC: '${{ env.MY_SEC }}'
      run: |
        echo $MY_SEC >> secrets.txt
        cat secrets.txt